/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafico;

import com.toedter.calendar.JDateChooser;
import datos.Ingreso;
import datos.Salida;
import java.util.Date;
import javax.swing.JOptionPane;
import logica.Registro;


/**
 *
 * @author Legarda
 */
public class Ventana extends javax.swing.JFrame {

    private Salida laopcion;
    private JDateChooser cjFecahHora;
    private String identificacion;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btRegistro = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        opIngreso = new javax.swing.JRadioButton();
        opSalida = new javax.swing.JRadioButton();
        cjIdentificacion = new javax.swing.JTextField();
        cjPlaca = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cjFechaHora = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PARQUEADERO MOTOS");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 20, 180, 18);

        btRegistro.add(opIngreso);
        opIngreso.setFont(new java.awt.Font("SERomanc", 1, 10)); // NOI18N
        opIngreso.setText("INGRESO");
        opIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opIngresoActionPerformed(evt);
            }
        });
        getContentPane().add(opIngreso);
        opIngreso.setBounds(220, 190, 120, 19);

        btRegistro.add(opSalida);
        opSalida.setFont(new java.awt.Font("SERomanc", 1, 10)); // NOI18N
        opSalida.setText("SALIDA");
        opSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(opSalida);
        opSalida.setBounds(340, 190, 90, 19);
        getContentPane().add(cjIdentificacion);
        cjIdentificacion.setBounds(50, 110, 160, 22);
        getContentPane().add(cjPlaca);
        cjPlaca.setBounds(230, 110, 180, 22);

        btGuardar.setFont(new java.awt.Font("SERomanc", 1, 10)); // NOI18N
        btGuardar.setText("GUARDAR");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btGuardar);
        btGuardar.setBounds(410, 277, 110, 20);

        btSalir.setFont(new java.awt.Font("SERomanc", 1, 10)); // NOI18N
        btSalir.setText("SALIR");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir);
        btSalir.setBounds(530, 277, 100, 20);

        jLabel2.setFont(new java.awt.Font("SERomanc", 1, 10)); // NOI18N
        jLabel2.setText("IDENTIFICACION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 90, 140, 11);

        jLabel3.setFont(new java.awt.Font("SERomanc", 1, 10)); // NOI18N
        jLabel3.setText("PLACA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 90, 60, 11);

        jLabel4.setFont(new java.awt.Font("SERomanc", 1, 10)); // NOI18N
        jLabel4.setText("FECHA Y HORA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 90, 130, 11);
        getContentPane().add(cjFechaHora);
        cjFechaHora.setBounds(430, 110, 180, 22);

        setSize(new java.awt.Dimension(654, 344));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed

       JOptionPane.showMessageDialog(this, "Se genero su registro");  // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarActionPerformed

    private void opSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSalidaActionPerformed
      this.clickOpcion(2);  // TODO add your handling code here:
    }//GEN-LAST:event_opSalidaActionPerformed

    private void opIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opIngresoActionPerformed
      this.clickOpcion(1);  // TODO add your handling code here:
    }//GEN-LAST:event_opIngresoActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
     }
         private void clickOpcion(int opcion){
        //JOptionPane.showMessageDialog(this, opcion);
        if (opcion == 1){
            this.laopcion = Salida.INGRESO;
        }else{
            this.laopcion = Salida.SALIDA;
        }
    }
         /*   private void crearRegistro(){
       
        String identificacion = cjIdentificacion.getText();
        Date fecha = cjFechaHora.getDate();//this.convertirStrinToDate(cjFechaCita.getText());
        
        Registro g = new Registro();
        Ingreso c = g.crearRegistro(identificacion, fecha, placa,  this.laopcion);
        if (c != null){
            this.cargaRegistro();
            JOptionPane.showMessageDialog(this, "Genero Registro ->"+c);
            
        }else{
            JOptionPane.showMessageDialog(this, "No lleno bien los datos");
        }
        
    }
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.ButtonGroup btRegistro;
    private javax.swing.JButton btSalir;
    private com.toedter.calendar.JDateChooser cjFechaHora;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextField cjPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton opIngreso;
    private javax.swing.JRadioButton opSalida;
    // End of variables declaration//GEN-END:variables





}
